const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  DECREASE_ITEM: 'DECREASE_ITEM',
  CLEAR_CART: 'CLEAR_CART',
};

export default CartActionTypes;
